name: 'Inputs Validation Action'
branding:
  icon: check-circle
  color: orange
description:
  'Provides a flexible way to validate the inputs of an action or a workflow'
author: 'Mustapha Belmokhtar'

inputs:
  validation-script:
    description: 'validation yaml script'
    required: false

  validation-script-file:
    description: 'validation yaml script file location, used only if the validation-script is not provided'
    required: false

# Define your outputs here.
outputs:
  validation-result:
    description: 'The validation result of the inputs'
runs:
  using: node20
  main: dist/index.js
