name: Test with a workflow with a script file

on:
  workflow_dispatch:
    inputs:
      input-b:
        description: input-b
        required: false
      milliseconds:
        description: milliseconds
        required: false
      time-to-live:
        required: false
        description: time-to-live
      enabled:
        description: enabled
        required: false

permissions:
  contents: read

jobs:
  test-job:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Input Validation
        uses: ./
        with:
          input-b: ${{ inputs.input-b }}
          milliseconds: ${{ inputs.milliseconds }}
          time-to-live: ${{ inputs.time-to-live }}
          enabled: ${{ inputs.enabled }}

          validation-script-file: ./.github/validation-script.yml
